version: '3.8'

services:
  db_checkout:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: checkout
      POSTGRES_DB: checkout
      POSTGRES_USER: checkout
    ports:
      - '5432:5432'
    volumes:
      - ./db_checkout:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
